-- Akshara High School: database schema (PostgreSQL)
--
-- Run once, from the project root, as the app user:
--   psql -U akshara_app -h localhost -d akshara_school -v ON_ERROR_STOP=1 -f database/schema.sql

BEGIN;

-- Admission enquiries submitted from the website (POST /api/enquiries)
CREATE TABLE enquiries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name   VARCHAR(100)  NOT NULL,
    date_of_birth  DATE          NOT NULL,
    applying_for   VARCHAR(20)   NOT NULL,
    parent_name    VARCHAR(100)  NOT NULL,
    phone          VARCHAR(15)   NOT NULL,
    email          VARCHAR(150)  NOT NULL,
    message        VARCHAR(1000),
    status         VARCHAR(20)   NOT NULL DEFAULT 'NEW'
                   CHECK (status IN ('NEW', 'CONTACTED', 'CLOSED')),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_enquiries_created_at ON enquiries (created_at DESC);
CREATE INDEX idx_enquiries_status ON enquiries (status);

-- Messages sent from the Contact page (POST /api/contact)
CREATE TABLE contact_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    email       VARCHAR(150)  NOT NULL,
    phone       VARCHAR(15),
    subject     VARCHAR(150)  NOT NULL,
    message     VARCHAR(1000) NOT NULL,
    is_read     BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_contact_messages_created_at ON contact_messages (created_at DESC);

-- School events (event_date is NULL until the date is announced)
CREATE TABLE events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(150)  NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    event_date   DATE,
    location     VARCHAR(150),
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_events_event_date ON events (event_date);

-- Gallery photos (image_url is NULL for placeholder tiles)
CREATE TABLE gallery_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(150) NOT NULL,
    description  VARCHAR(500),
    category     VARCHAR(50)  NOT NULL,
    image_url    VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_gallery_items_category ON gallery_items (category);

-- Login accounts for admins and students.
-- username is the admin's email, or the student's admission number.
-- password_hash holds a BCrypt hash, never the password itself.
CREATE TABLE app_users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              VARCHAR(100) NOT NULL,
    password_hash         VARCHAR(100) NOT NULL,
    full_name             VARCHAR(100) NOT NULL,
    role                  VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN', 'STUDENT')),
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    must_change_password  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_app_users_username ON app_users (lower(username));

-- Extra details for student accounts (kept to the minimum)
CREATE TABLE student_profiles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL UNIQUE
                    REFERENCES app_users (id) ON DELETE CASCADE,
    class_name      VARCHAR(20) NOT NULL,
    section         VARCHAR(10),
    guardian_name   VARCHAR(100),
    guardian_phone  VARCHAR(15)
);

COMMIT;